name: cv_hw3_task2_local
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.10.0
      - torchvision==0.25.0
      - -r requirements-local.txt
